[package]
name = "mini_lms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.17"
log = "0.4.17"
tokio = { version = "1.22.0", features = ["full"] }
